### ISSUE TITLE
Master branch should be protected

### ISSUE THREAD

**Issue by ajdubovoy** [lewagon/dotfiles#151]
Context: https://github.com/lewagon/dotfiles/commit/8e0e5fa4f79e5675aaa275ccf365dedf02643738

It looks like someone accidentally committed to `master`, which created temporary weird effects for students on setup day 🙀 

Since this is a...fairly important repo, can we please lock the `master` branch? I'd do it myself but I don't have permissions. Maybe @Eschults, you have to do it?

Thanks so much!

**Comment by Eschults** [comment]
👋 I added branch rules this morning, also the repo has limited Write accesses since the beginning, so not sure what happened here 🤔 
<img width="1532" alt="Screen Shot 2023-10-09 at 12 49 28" src="https://github.com/lewagon/dotfiles/assets/8090140/15491c3c-39c9-4442-8e8a-b05a913246b1">
<img width="1575" alt="Screen Shot 2023-10-09 at 13 36 15" src="https://github.com/lewagon/dotfiles/assets/8090140/f1963aec-eb10-446c-ab0f-4607e0e397f5">

Branch protection rules should prevent this from happening in the future 👌

**Comment by ajdubovoy** [comment]
Thank you!!
