### ISSUE TITLE
nvm load does not work for Mac users

### ISSUE THREAD

**Issue by trouni** [lewagon/dotfiles#80]
The following lines to load `nvm` do not work on Mac (seems like these are taken from the Ubuntu setup):

```zsh
# Load nvm (to manage your node versions)
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
```

These are the lines given by the terminal after running `brew install nvm` from one of the students, but I believe there were some slightly different folders depending on the laptops (one of them was pointing to the `homebrew` folder if I recall properly):

```zsh
export NVM_DIR="$HOME/.nvm"
 [ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh" # This loads nvm
 [ -s "/usr/local/opt/nvm/etc/bash_completion.d/nvm" ] && . "/usr/local/opt/nvm/etc/bash_completion.d/nvm" # This loads nvm bash_completion
```

**Comment by trouni** [comment]
Saw you made the previous update, @dmilon

**Comment by dmilon** [comment]
:wave: @trouni. Thank you for your report :pray: I've just made [an update](https://github.com/lewagon/dotfiles/commit/40042bdcaec03286a332d2a3eaa55f6277c89d82) to branch the path depending on the OS.

**Comment by dmilon** [comment]
@trouni after further investigation, `nvm` should not be installed with `brew` on mac but with the official script. This installation allows to use `~/.nvm/nvm.sh` as PATH for the `nvm` command. I've just reverted the changes I had previously made and updated [the setup instructions](https://github.com/lewagon/setup/blob/master/UBUNTU.md#installing-node-with-nvm) to use the script instead of `brew.
